### ISSUE TITLE
Hope to obtain the environment configuration of Mutahunter

### ISSUE THREAD

**Issue by zonewenke** [codeintegrity-ai/mutahunter#24]
Mutahunter is a great work in my opinion. I hope that after pulling the open-source code from GitHub, I can configure it and make the code run. However, the README page of Mutahunter is the user's instruction manual rather than the developer's. Could you please tell me some necessary environment configurations? Thank you very much. (The configuration I currently know is Python 3.11+)

**Comment by jungs1** [comment]
The only required environment configuration is setting the LLM API key. After installing the mutahunter package via pip, you just need to set your API key by running export OPENAI_API_KEY="your_key_here". Does this help?

**Comment by zonewenke** [comment]
- When I had my environment set up and was ready to try # Java Maven Example, I encountered the issue of [WinError 2] The system cannot find the file specified. I have tried some solutions, but none of them worked. If anyone has experience in solving similar problems, please let me know, I would be very grateful!

  Here are some details about this issue.

- mvn test (This step is fine)

```python
(E:\conda_envs\mutahunter) PS E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven> mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.example:demo >--------------------------
[INFO] Building demo 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.7:prepare-agent (default) @ demo ---
[INFO] argLine set to -javaagent:E:\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.7\\org.jacoco.agent-0.8.7-runtime.jar=destfile=E:\\github_projects\\LLM-unittest\\mutahunter-main\\examples\\java_maven\\target\\jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ demo ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running BankAccountTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 s - in BankAccountTest
[INFO] 
[INFO] Results:
[INFO]
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.7:report (report) @ demo ---
[INFO] Loading execution data file E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven\target\jacoco.exec
[INFO] Analyzed bundle 'demo' with 1 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.327 s
[INFO] Finished at: 2024-11-23T12:23:41+08:00
[INFO] ------------------------------------------------------------------------
```

- export OPENAI_API_KEY=your-key-goes-here. 

  - In this step, I replaced "your-key-goes-here" with my own key, which I have used in another project A and is executable. The only difference is that in A, both base_url and key were set simultaneously. (In this step, I changed "export" to "set")

- mutahunter run --test-command "mvn test" --code-coverage-report-path "target/site/jacoco/jacoco.xml" --coverage-type jacoco --model "gpt-4o-mini",

  - When I run this command, an error occurred: " [WinError 2] The system cannot find the file specified", as shown below.

  ```python
  (E:\conda_envs\mutahunter) PS E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven> mutahunter run --test-command "mvn test" --code-coverage-report-path "target/site/jacoco/jacoco.xml" --coverage-type jacoco --model "gpt-4o-mini"                                                                                                                            
  2024-11-23 11:58:26,059 INFO: Starting Coverage Analysis...
  2024-11-23 11:58:26,060 ERROR: Coverage analysis failed: Failed to complete coverage analysis: [WinError 2] 系统找不到指定的文件。
  ```

  1.When I search for this file using the cd command, I can find it.

  ```python
  (E:\conda_envs\mutahunter) PS E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven> cd target/site/jacoco
  (E:\conda_envs\mutahunter) PS E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven\target\site\jacoco> ls
  
  
      目录: E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven\target\site\jacoco
  
  
  Mode                 LastWriteTime         Length Name
  ----                 -------------         ------ ----
  d-----        2024/11/15     17:44                com.example
  d-----        2024/11/15     17:44                jacoco-resources
  d-----        2024/11/21     18:07                logs
  -a----        2024/11/22     12:53           3946 index.html
  -a----        2024/11/22     12:38          37214 jacoco-sessions.html
  -a----        2024/11/22     12:38            235 jacoco.csv
  -a----        2024/11/23     11:10           7552 jacoco.xml
  -a----        2024/11/21     18:07          28672 mutahunter.db
  ```

  2.When I run the mutahunter run command, specifying the file as jacoco.xml under java_maven,

  I still get the error [WinError 2] The system cannot find the file specified.

  ```python
  (E:\conda_envs\mutahunter) PS E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven> mutahunter run --test-command "mvn test" --code-coverage-report-path "jacoco.xml" --coverage-type jacoco --model "gpt-4o-mini"
  2024-11-21 19:24:29,238 INFO: Starting Coverage Analysis...
  2024-11-21 19:24:29,239 ERROR: Coverage analysis failed: Failed to complete coverage analysis: [WinError 2] 系统找不到指定的文件。
  ```

  3.The path separator in Windows environment may cause issues. Try running the command with the following variations:

  Using forward slash

  - ```
    /
    ```

    Replace backslash:

    ```python
    mutahunter run --test-command "mvn test" --code-coverage-report-path "E:/github_projects/LLM-unittest/mutahunter-main/examples/java_maven/target/site/jacoco/jacoco.xml" --coverage-type jacoco --model "gpt-4o-mini"
    ```

  - with double backslashes：

    ```
    \\
    ```

    ```python
    mutahunter run --test-command "mvn test" --code-coverage-report-path "E:\\github_projects\\LLM-unittest\\mutahunter-main\\examples\\java_maven\\target\\site\\jacoco\\jacoco.xml" --coverage-type jacoco --model "gpt-4o-mini"
    ```

​		The above commands have been tried without success.

- When I checked my Maven and Java configurations, I didn't find any issues.

  - ```python
    (E:\conda_envs\mutahunter) PS E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven\target\site\jacoco> mvn -v
    Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
    Maven home: D:\apache-maven-3.6.3\bin\..
    Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: D:\Java\JDK\jre
    Default locale: zh_CN, platform encoding: GBK
    OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
    (E:\conda_envs\mutahunter) PS E:\github_projects\LLM-unittest\mutahunter-main\examples\java_maven\target\site\jacoco> java -version
    java version "1.8.0_212"
    Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
    Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
    ```

    If you have any suggestions, I would be very grateful.

**Comment by luoyq-Rockey** [comment]
Faced the same problem,the steps are as follows:

**Comment by jungs1** [comment]
Thanks for your interest! I’ve removed the dependency on coverage and simplified the code significantly. Could you please pull the latest code and try running the following command?
The process is now much simpler, and you only need to specify the source and test file paths:

```shell
mutahunter run --test-command "mvn clean test" --model "gpt-4o-mini" --source-path "src/main/java/com/example/BankAccount.java" --test-path "src/test/java/BankAccountTest.java"            
```

**Comment by mUSael85** [comment]
@jungs1 Hi there. I'd like to reply because I was encounting the same errors. So I pulled the latest version of the code as you've said, but can't install it anymore. Here is what I've tried:

1.  Run pip install https://github.com/codeintegrity-ai/mutahunter as mentioned in the README.md, but obtained the following error:

```bashspy -3.12 -m pip install https://github.com/codeintegrity-ai/mutahunter
Collecting https://github.com/codeintegrity-ai/mutahunter
  Downloading https://github.com/codeintegrity-ai/mutahunter
     - 277.3 kB 3.1 MB/s 0:00:00
  ERROR: Cannot unpack file C:\Users\samue\AppData\Local\Temp\pip-unpack-tttzrvs7\mutahunter (downloaded from C:\Users\samue\AppData\Local\Temp\pip-req-build-9tttp1_u, content-type: text/html; charset=utf-8); cannot detect archive format`

this is due to the fact pip can install packages accepting +git"repositoryurl".git;

2. Next I tried what I've just said so

**Comment by mUSael85** [comment]
@jungs1 Since I was encountering the same errors I pulled the latest version of the code as you've said, but can't install. I'm on Windows 10 and I'm using Python 3.12.9. Here is what I've tried:

1. Run `pip install https://github.com/codeintegrity-ai/mutahunter` as mentioned in the README.md, but obtained the following error:

```bash
py -3.12 -m pip install https://github.com/codeintegrity-ai/mutahunter
Collecting https://github.com/codeintegrity-ai/mutahunter
  Downloading https://github.com/codeintegrity-ai/mutahunter
     - 277.3 kB 3.1 MB/s 0:00:00
  ERROR: Cannot unpack file C:\Users\samue\AppData\Local\Temp\pip-unpack-tttzrvs7\mutahunter (downloaded from C:\Users\samue\AppData\Local\Temp\pip-req-build-9tttp1_u, content-type: text/html; charset=utf-8); cannot detect archive format
```

this is due to the fact pip can install packages accepting +git"repositoryurl".git;

2. Next I tried what I've just said:

```bash
ERROR: Invalid requirement: '+githttps://github.com/codeintegrity-ai/mutahunter.git': Expected package name at the start of dependency specifier
    +githttps://github.com/codeintegrity-ai/mutahunter.git
    ^
```

what I'm doing wrong here?

3. Tried the previous command mentioned in repository, simply:

```bash
pip install mutahunter
```

obtaining this output here:

```bash
py -3.12 -m pip install mutahunter
Collecting mutahunter
  Using cached mutahunter-1.3.0-py3-none-any.whl.metadata (43 kB)
Collecting tree-sitter==0.21.3 (from mutahunter)
  Using cached tree_sitter-0.21.3-cp312-cp312-win_amd64.whl.metadata (10 kB)
Collecting tree_sitter_languages==1.10.2 (from mutahunter)
  Using cached tree_sitter_languages-1.10.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting tqdm (from mutahunter)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting grep_ast (from mutahunter)
  Using cached grep_ast-0.8.1-py3-none-any.whl.metadata (2.7 kB)
Collecting pygments (from mutahunter)
  Using cached pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)
Collecting networkx (from mutahunter)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from mutahunter)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting litellm (from mutahunter)
  Using cached litellm-1.63.8-py3-none-any.whl.metadata (36 kB)
Collecting numpy (from mutahunter)
  Using cached numpy-2.2.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting scipy (from mutahunter)
  Using cached scipy-1.15.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting tree-sitter-language-pack (from grep_ast->mutahunter)
  Using cached tree_sitter_language_pack-0.6.0-cp39-abi3-win_amd64.whl.metadata (20 kB)
Collecting pathspec (from grep_ast->mutahunter)
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Collecting MarkupSafe>=2.0 (from jinja2->mutahunter)
  Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Collecting aiohttp (from litellm->mutahunter)
  Using cached aiohttp-3.11.13-cp312-cp312-win_amd64.whl.metadata (8.0 kB)
Collecting click (from litellm->mutahunter)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting httpx>=0.23.0 (from litellm->mutahunter)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting importlib-metadata>=6.8.0 (from litellm->mutahunter)
  Using cached importlib_metadata-8.6.1-py3-none-any.whl.metadata (4.7 kB)
Collecting jsonschema<5.0.0,>=4.22.0 (from litellm->mutahunter)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting openai>=1.66.1 (from litellm->mutahunter)
  Using cached openai-1.66.3-py3-none-any.whl.metadata (25 kB)
Collecting pydantic<3.0.0,>=2.0.0 (from litellm->mutahunter)
  Using cached pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
Collecting python-dotenv>=0.2.0 (from litellm->mutahunter)
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting tiktoken>=0.7.0 (from litellm->mutahunter)
  Using cached tiktoken-0.9.0-cp312-cp312-win_amd64.whl.metadata (6.8 kB)
Collecting tokenizers (from litellm->mutahunter)
  Using cached tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting colorama (from tqdm->mutahunter)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting anyio (from httpx>=0.23.0->litellm->mutahunter)
  Using cached anyio-4.8.0-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi (from httpx>=0.23.0->litellm->mutahunter)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx>=0.23.0->litellm->mutahunter)
  Using cached httpcore-1.0.7-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx>=0.23.0->litellm->mutahunter)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.23.0->litellm->mutahunter)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting zipp>=3.20 (from importlib-metadata>=6.8.0->litellm->mutahunter)
  Using cached zipp-3.21.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=22.2.0 (from jsonschema<5.0.0,>=4.22.0->litellm->mutahunter)
  Using cached attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema<5.0.0,>=4.22.0->litellm->mutahunter)
  Using cached jsonschema_specifications-2024.10.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema<5.0.0,>=4.22.0->litellm->mutahunter)
  Using cached referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema<5.0.0,>=4.22.0->litellm->mutahunter)
  Using cached rpds_py-0.23.1-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Collecting distro<2,>=1.7.0 (from openai>=1.66.1->litellm->mutahunter)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting jiter<1,>=0.4.0 (from openai>=1.66.1->litellm->mutahunter)
  Using cached jiter-0.9.0-cp312-cp312-win_amd64.whl.metadata (5.3 kB)
Collecting sniffio (from openai>=1.66.1->litellm->mutahunter)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting typing-extensions<5,>=4.11 (from openai>=1.66.1->litellm->mutahunter)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->litellm->mutahunter)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.27.2 (from pydantic<3.0.0,>=2.0.0->litellm->mutahunter)
  Using cached pydantic_core-2.27.2-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Collecting regex>=2022.1.18 (from tiktoken>=0.7.0->litellm->mutahunter)
  Using cached regex-2024.11.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting requests>=2.26.0 (from tiktoken>=0.7.0->litellm->mutahunter)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->litellm->mutahunter)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->litellm->mutahunter)
  Using cached aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->litellm->mutahunter)
  Using cached frozenlist-1.5.0-cp312-cp312-win_amd64.whl.metadata (14 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->litellm->mutahunter)
  Using cached multidict-6.1.0-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting propcache>=0.2.0 (from aiohttp->litellm->mutahunter)
  Using cached propcache-0.3.0-cp312-cp312-win_amd64.whl.metadata (10 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->litellm->mutahunter)
  Using cached yarl-1.18.3-cp312-cp312-win_amd64.whl.metadata (71 kB)
Collecting huggingface-hub<1.0,>=0.16.4 (from tokenizers->litellm->mutahunter)
  Using cached huggingface_hub-0.29.3-py3-none-any.whl.metadata (13 kB)
INFO: pip is looking at multiple versions of tree-sitter-language-pack to determine which version is compatible with other requirements. This could take a while.
Collecting tree-sitter-language-pack (from grep_ast->mutahunter)
  Using cached tree_sitter_language_pack-0.5.0-cp39-abi3-win_amd64.whl.metadata (20 kB)
  Using cached tree_sitter_language_pack-0.4.0-cp39-abi3-win_amd64.whl.metadata (20 kB)
  Using cached tree_sitter_language_pack-0.3.1-cp39-abi3-win_amd64.whl.metadata (20 kB)
  Using cached tree_sitter_language_pack-0.3.0-cp39-abi3-win_amd64.whl.metadata (20 kB)
  Using cached tree_sitter_language_pack-0.2.0.tar.gz (35.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached tree_sitter_language_pack-0.1.2.tar.gz (35.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached tree_sitter_language_pack-0.1.1.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\samue\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\samue\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\samue\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\samue\AppData\Local\Temp\pip-build-env-dh05gby0\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\samue\AppData\Local\Temp\pip-build-env-dh05gby0\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\samue\AppData\Local\Temp\pip-build-env-dh05gby0\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 66, in <module>
        File "<string>", line 25, in get_mapped_parsers
      FileNotFoundError: [WinError 3] Impossibile trovare il percorso specificato: 'C:\\Users\\samue\\AppData\\Local\\Temp\\pip-install-zm0f4dm2\\tree-sitter-language-pack_77a5be20eb564698acc8f15277b4bebb\\parsers'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

4. Tried to install mutahunter in .venv, also obtaining the above mentioned problem.

How can I solve these issues? Can I install mutahunter from the repository itself? How can I do so if possible?

Can you please be clear regarding setting correctly the environment? Is there a specific Python version to be used?

Thank you very much in advance

**Comment by jungs1** [comment]
Appreciate your patience. The issue was due to the grep-ast dependency, and I’ve now resolved it. Please try installing again, and let me know if you run into any further issues!

**Comment by jungs1** [comment]
You’re right. earlier versions of mutahunter did include the ability to generate unit tests using LLMs. However, my current focus is on making it more mutation-specific to stay aligned with its core purpose. That said, I’m open to revisiting test generation in the future if there’s enough interest!

**Comment by luoyq-Rockey** [comment]
> Thanks for your interest! I’ve removed the dependency on coverage and simplified the code significantly. Could you please pull the latest code and try running the following command? The process is now much simpler, and you only need to specify the source and test file paths:
> 
> mutahunter run --test-command "mvn clean test" --model "gpt-4o-mini" --source-path "src/main/java/com/example/BankAccount.java" --test-path "src/test/java/BankAccountTest.java"

Hello, I have come back. According to your guidance, I have pulled up the latest code and executed the order you provided. Now there is a new problem,like this 
`
(.venv) PS D:\LLM\mutahunter\examples\java_maven> mutahunter run --test-command "mvn clean test" --model "gpt-4o-mini" --source-path "src/main/java/com/example/BankAccount.java" --test-path "src/test/java/BankAccountTest.java"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\LLM\mutahunter\.venv\Scripts\mutahunter.exe\__main__.py", line 7, in <module>
  File "D:\LLM\mutahunter\.venv\Lib\site-packages\mutahunter\main.py", line 114, in run
    controller.run()
    self.test_runner.dry_run()
  File "D:\LLM\mutahunter\.venv\Lib\site-packages\mutahunter\core\runner.py", line 18, in dry_run
    result = self._run_test_command(self.test_command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\mutahunter\.venv\Lib\site-packages\mutahunter\core\runner.py", line 34, in _run_test_command
    return subprocess.run(split(test_command), cwd=os.getcwd())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_3.11.9\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_3.11.9\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\python_3.11.9\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

`

**Comment by luoyq-Rockey** [comment]
> > Thanks for your interest! I’ve removed the dependency on coverage and simplified the code significantly. Could you please pull the latest code and try running the following command? The process is now much simpler, and you only need to specify the source and test file paths:感谢您的关注！我消除了对覆盖率的依赖并大大简化了代码。您能否提取最新代码并尝试运行以下命令？现在，该过程变得更加简单，您只需指定源和测试文件路径：
> > mutahunter run --test-command "mvn clean test" --model "gpt-4o-mini" --source-path "src/main/java/com/example/BankAccount.java" --test-path "src/test/java/BankAccountTest.java"mutahunter run --test-command “mvn clean test” --model “gpt-4o-mini” --source-path “src/main/java/com/example/BankAccount.java” --test-path “src/test/java/BankAccountTest.java”
> 
> Hello, I have come back. According to your guidance, I have pulled up the latest code and executed the order you provided. Now there is a new problem,like this 您好，我回来了。根据您的指导，我已经拉取了最新的代码并执行了您提供的订单。现在有一个新问题，比如[@jungs1](https://github.com/jungs1)
> 
> ```
> (.venv) PS D:\LLM\mutahunter\examples\java_maven> mutahunter run --test-command "mvn clean test" --model "gpt-4o-mini" --source-path "src/main/java/com/example/BankAccount.java" --test-path "src/test/java/BankAccountTest.java"
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "D:\LLM\mutahunter\.venv\Scripts\mutahunter.exe\__main__.py", line 7, in <module>
>   File "D:\LLM\mutahunter\.venv\Lib\site-packages\mutahunter\main.py", line 114, in run
>     controller.run()
>     self.test_runner.dry_run()
>   File "D:\LLM\mutahunter\.venv\Lib\site-packages\mutahunter\core\runner.py", line 18, in dry_run
>     result = self._run_test_command(self.test_command)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\LLM\mutahunter\.venv\Lib\site-packages\mutahunter\core\runner.py", line 34, in _run_test_command
>     return subprocess.run(split(test_command), cwd=os.getcwd())
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\python_3.11.9\Lib\subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\python_3.11.9\Lib\subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "D:\python_3.11.9\Lib\subprocess.py", line 1538, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> ```

change the runner.py  like  @mUSael85  can be work! 

```
return subprocess.run(split(test_command), cwd=os.getcwd(), shell=True)

def run_test(self, params: dict) -> subprocess.CompletedProcess:
    module_path = params["module_path"]
    replacement_module_path = params["replacement_module_path"]
    test_command = params["test_command"]
    backup_path = f"{module_path}.bak"
    try:
        self.replace_file(module_path, replacement_module_path, backup_path)
        result = subprocess.run(
            split(test_command),
            text=True,
            capture_output=True,
            cwd=os.getcwd(),
            timeout=30,
            shell=True
        )
```
